### ISSUE TITLE
关于在使用Z.EntityFramework.Plus遇到的问题

### ISSUE THREAD

**Issue by Im-Kevin** [dotnetcore/sharding-core#126]
我发现在使用Z.EntityFramework.Plus的DeferredXXX时会报一个
Unable to cast object of type 'ShardingCore.EFCores.ShardingQueryCompiler' to type 'Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler'
错误,我看你那边是继承于IQueryCompiler的,而这个应该是转换成QueryCompiler导致的
是否有机会将IQueryCompiler改成QueryCompiler

**Comment by xuejmnet** [comment]
@Im-Kevin 批处理请查看文档批处理说明，支持所有三方批处理框架

**Comment by Im-Kevin** [comment]
可能你理解错我意思了,这个不是批处理,而是延迟执行,或者缓存,例如Z.EntityFramework.Plus的FromCache和Future,
而用到的是DeferredCount,这种也需要用批处理的方式吗

**Comment by xuejmnet** [comment]
@因为三方框架众多，你是用zzz别人使用bulk或者zack所以这边统一采用shardingcore的批处理解决方案，先获取真实的dncontext后操作，如果是查询的话需要后续进行适配，但是非查询操作建议查看批处理文档

**Comment by Im-Kevin** [comment]
OK,好的,麻烦了

**Comment by xuejmnet** [comment]
@Im-Kevin 您可以将用到的情况进行反馈出来因为可能我本身也并是会涉及到三方所有的功能，其中肯定有考虑欠周的需要慢慢兼容解决
