### ISSUE TITLE
是否有办法让分表查找可以按顺序查找

### ISSUE THREAD

**Issue by Im-Kevin** [dotnetcore/sharding-core#127]
我发现这个跨表查找的时候是乱序的,找不到规律
我想让它倒序查找
![image](https://user-images.githubusercontent.com/15227529/155996088-f73a5b55-cfd8-431c-a0ef-2eb7d66f8ae6.png)
这是我查找的代码
![image](https://user-images.githubusercontent.com/15227529/155996145-c9abaaa2-d4e3-46e3-be73-aceb5814262c.png)
这是我分页的代码

**Comment by Im-Kevin** [comment]
我是按日分表的

**Comment by Im-Kevin** [comment]
![image](https://user-images.githubusercontent.com/15227529/155996385-21eb56c9-23bf-4bc0-8fbb-2a2d375a5deb.png)
然后这是我分页查找的一次结果,可以看到他是先从2月22查找然后再2月27,最后2月17

**Comment by xuejmnet** [comment]
@Im-Kevin 如果你是普通的查询非分页查询的那么可以参考 [blog](https://www.cnblogs.com/xuejiaming/p/15848454.html)

**Comment by xuejmnet** [comment]
@Im-Kevin  
- 分页:分页是两步 count+tolist,这边sharding core进行了优化,保证了高性能的tolist 可以参考[blog](https://www.cnblogs.com/xuejiaming/p/15237878.html) ,
- 非分页:如果你是需要普通的顺序,比如first或者tolist或者last或者any之类的可以参考[blog](https://www.cnblogs.com/xuejiaming/p/15848454.html)

**Comment by xuejmnet** [comment]
哪怕你配置了分页但是如果你没有使用ToShardingPage的方法的话也是不会生效的,因为高性能分页需要使用前一次的count作为依据

**Comment by Im-Kevin** [comment]
可以不count做分页吗,count有时候太耗性能了

**Comment by xuejmnet** [comment]
@Im-Kevin  [分页参考](https://github.com/dotnetcore/sharding-core/blob/b07af78224f52280fd02c48487f01788d9fa08d9/samples/Sample.BulkConsole/Program.cs#L134)

**Comment by xuejmnet** [comment]
可以就是[这一篇博客](https://www.cnblogs.com/xuejiaming/p/15848454.html)

**Comment by Im-Kevin** [comment]
好的,我看看先

**Comment by xuejmnet** [comment]
因为功能是刚出的,我还未来得及写文档不过原理一样的,因为你是时间排序所以默认的ShardingTailComparer就是[202201,202202,202203....]这样的一个正序,所以为了让他复核倒序你需要做的就是第二个参数改成false,那么程序默认的分片排序就是[202203，202202，202201.....]，然后在对他进行ConnectionMode的配置并发1或者2即可

**Comment by Im-Kevin** [comment]
好的,谢谢

**Comment by Im-Kevin** [comment]
我刚才试了下,这个好像不支持ToList这些获取数组的方法

**Comment by xuejmnet** [comment]
@Im-Kevin 我刚才看了源码了好像是的我这边这两天做一下take的支持,实在不好意思,不过你说的顺序,应该不会有关系的,因为他是并行执行的,只是日志打印的顺序是乱的其实是聚合的时候有顺序的

**Comment by Im-Kevin** [comment]
是我应该感谢你提供了一个这么好的库,有些东西需要慢慢完善,急不来的,已经非常不错了

**Comment by Im-Kevin** [comment]
然后我刚才测了一下,发现这个ShardingTailComparer的顺序需要和AddOrder一致,就是前一个设置的是顺序,那后一个也得设置顺序,设置反了会导致输出的数据错误,如果要写文档,建议将这个讲清楚点,麻烦你了

> 因为功能是刚出的,我还未来得及写文档不过原理一样的,因为你是时间排序所以默认的ShardingTailComparer就是[202201,202202,202203....]这样的一个正序,所以为了让他复核倒序你需要做的就是第二个参数改成false,那么程序默认的分片排序就是[202203，202202，202201.....]，然后在对他进行ConnectionMode的配置并发1或者2即可

**Comment by xuejmnet** [comment]
> 然后我刚才测了一下,发现这个ShardingTailComparer的顺序需要和AddOrder一致,就是前一个设置的是顺序,那后一个也得设置顺序,设置反了会导致输出的数据错误,如果要写文档,建议将这个讲清楚点,麻烦你了

这个我会注意的因为目前还没写文档所以基本上没多少人用这个功能,这边在不断完善中,谢谢提醒

**Comment by xuejmnet** [comment]
@Im-Kevin 这边问下您的id是什么，雪花id吗还是自增id,如果是自增id的话你那种写法依然无法确定表,需要将上一次时间带过来才可以,如果是雪花id的话这边建议您使用多字段分片,反解析出时间

**Comment by xuejmnet** [comment]
@Im-Kevin [多字段分片解决方案](https://www.cnblogs.com/xuejiaming/p/15728340.html)

**Comment by xuejmnet** [comment]
@Im-Kevin 当然如果是自增id的话可以在redis里存一分最大id对应的表后缀,这样也可以通过添加额外分片字段来实现多字段分片,也是可以的和雪花id有一样的效果,路由里面可以通过添加redis或者别的中间件来进行辅助分片

**Comment by Im-Kevin** [comment]
雪花Id,我已经安装你的例子做了解析的

**Comment by Im-Kevin** [comment]
![image](https://user-images.githubusercontent.com/15227529/156005488-0d3715f7-b03d-49d3-ae04-0da16ce66542.png)

**Comment by xuejmnet** [comment]
@Im-Kevin 嗯如果是雪花id那么可以自行解析,如果是自增id需要redis之类的工具

**Comment by Im-Kevin** [comment]
嗯,明白

**Comment by xuejmnet** [comment]
@Im-Kevin 我已经发布了最新版本针对`GetEnumerator()`,`ToList()`方法添加了顺序查询的熔断支持(同步+异步方法)x.4.1.9+

**Comment by xuejmnet** [comment]
如果没效果请检测MaxQueryConnectionsLimit，或者在EntitiyQueryConfiguration处配置,又或者在查询的时候使用扩展方法`.UseConnectionMode(2)`来限制,只有当系统才有连接数限制才会生效,在内存限制的时候是不会生效的,(系统自动判断你只需要填写并发数即可)

**Comment by Im-Kevin** [comment]
好的,谢谢,我看看先

**Comment by Im-Kevin** [comment]
我刚才试了下，使用扩展方法UseConnectionMode是正常的,但是我找不到全局设置MaxQueryConnectionsLimit的属性,因为LimitMethodNameEnum和CircuitBreakerMethodNameEnum都没有List的枚举值

**Comment by xuejmnet** [comment]
@Im-Kevin 实在是抱歉,应该是那边枚举忘记了,全局的话在AddConfig那边可以设置链接数的并发限制,我晚上更新下支持EntityQueryConfiguration处也进行enumerator的连接数限制
![image](https://user-images.githubusercontent.com/18061232/156123381-ea461b28-e56f-4ce6-b55f-c526fb21dea9.png)

**Comment by xuejmnet** [comment]
升级到x.4.1.10+版本默认IEntityQueryConfiguration增加了默认没有排序的时候`Enumerator`使用某某排序,和`Enumerator`的查询默认限制连接数

**Comment by xuejmnet** [comment]
@Im-Kevin 是否已经解决了😁

**Comment by Im-Kevin** [comment]
已经解决了, 不过我发现你这个分表插件有一个bug,如果select的是一个匿名类,会报空指针异常

**Comment by xuejmnet** [comment]
@Im-Kevin 不会吧有具体的错误日志吗麻烦了我这边看看,因为我单元测试里面应该都有测试过得

**Comment by Im-Kevin** [comment]
就是那个Object Instance XXX的,具体我没记下来,但是我反复试过了,其他都没变,只是将匿名类换成实体类就正常了

**Comment by Im-Kevin** [comment]
我试试写个demo看看

**Comment by xuejmnet** [comment]
@Im-Kevin 如果有堆栈信息那就最好了

**Comment by Im-Kevin** [comment]
at ShardingCore.Extensions.ExpressionExtension.GetValueByExpression(Object obj, String propertyExpression)
   
![image](https://user-images.githubusercontent.com/15227529/156535438-f2e50082-38d9-4418-b23d-293b106a5ff9.png)

**Comment by Im-Kevin** [comment]
我猜跟分页有关系

**Comment by Im-Kevin** [comment]
因为我没有配置分页这些,则不会有这个错误

**Comment by Im-Kevin** [comment]
我先试试,可能跟表达式关系不大

**Comment by xuejmnet** [comment]
@Im-Kevin 这个问题应该是我在获取你分片字段对应的表达式的时候可能哪个值的对象是null 比如o.shardingkey==a.name这个时候如果a是null就会报错但是具体不确定

**Comment by Im-Kevin** [comment]
分片字段都不是空的

**Comment by Im-Kevin** [comment]
![image](https://user-images.githubusercontent.com/15227529/156537846-a64a4787-7097-4337-9729-9cd89dc49a2d.png)

**Comment by Im-Kevin** [comment]
这是我刚才试的一个demo

**Comment by Im-Kevin** [comment]
已经执行了

**Comment by Im-Kevin** [comment]
![image](https://user-images.githubusercontent.com/15227529/156538405-1ccd0f4c-3bca-4f96-9c3b-72a17fe63c3b.png)

**Comment by Im-Kevin** [comment]
旧版本不会出现这个问题,应该是这次分页导致的

**Comment by Im-Kevin** [comment]
你那边是重现了吗

**Comment by Im-Kevin** [comment]
这个不急,我已经用替代方案做了,影响不大

**Comment by xuejmnet** [comment]
@Im-Kevin 我这边已经排查出问题了,是因为你orderby 了id属性而没有对齐进行select,导致程序无法正常排序,你可以尝试在匿名函数里面select id

**Comment by xuejmnet** [comment]
@Im-Kevin 后续会进行对语句的改写优化,再该种情况下会进行改写select给你们额外添加对应的属性但是返回结果还是用你们的来保证用户的无感操作

**Comment by Im-Kevin** [comment]
不知道为什么我突然重现不了,但是我记得之前是有select id也一样会出现的,先这样吧,之后遇到了再说

**Comment by xuejmnet** [comment]
@Im-Kevin 最新版本[x.4.2.4+]测试后应该是复核您的要求的如果没什么问题我就关闭了
