### ISSUE TITLE
是否支持TableAttribute

### ISSUE THREAD

**Issue by shaosu** [dotnetcore/sharding-core#129]
[Table("MyUser")]   // 表格名称与类型名称不同时,如何实现;
    public class User
    {
    }

**Comment by xuejmnet** [comment]
支持和原先使用efcore一样，我自己只是喜欢配置和对象分离，可以通过tableattribute+dbset也是支持的

**Comment by xuejmnet** [comment]
@shaosu  你可以尝试一下和原先efcore用attribute+dbset是一样的

**Comment by shaosu** [comment]
不分表可以用原先的DbSet
我直接修改IEntityType 的扩展函数GetEntityTypeTableName,增加了一句也是可以获取表格自定义名称的,如下
`            var tableName = entityType.GetTableName();
            string tableName;
            var nnn = entityType.ClrType.GetCustomAttributes(typeof(TableAttribute), false) as TableAttribute[];
            if (nnn.Length > 0)
            {
                tableName = nnn[0].Name;
            }
            else
            {
                tableName = entityType.GetTableName();
            } `

**Comment by xuejmnet** [comment]
@shaosu 什么意思，你现在是可以还是不可以呢

**Comment by xuejmnet** [comment]
@shaosu 完全不需要啊默认就是支持的为什么需要多此一举呢,
![image](https://user-images.githubusercontent.com/18061232/156885924-c7ac4570-4482-4d5a-be9d-bba235274572.png)
![image](https://user-images.githubusercontent.com/18061232/156885932-9501642e-ae70-48c6-90e1-1c7fcd7e36cb.png)
![image](https://user-images.githubusercontent.com/18061232/156885945-90749edd-d2f4-4f62-8ddf-f5413665db09.png)

**Comment by shaosu** [comment]
我是拿Sample.MySql那个工程测试的,测试时只改了连接字符串和加了TableAttribute 
![$Z8T`C}NBVF@ SM3_ M~XR7](https://user-images.githubusercontent.com/12237247/156904207-c0f09b09-7ed2-4d25-8647-6b3e6f7e0f2f.png)

**Comment by xuejmnet** [comment]
> 我是拿Sample.MySql那个工程测试的,测试时只改了连接字符串和加了TableAttribute 
> 
> ![$Z8T`C}NBVF@ SM3_ M~XR7](https://user-images.githubusercontent.com/12237247/156904207-c0f09b09-7ed2-4d25-8647-6b3e6f7e0f2f.png)
> 
> 
> 
> 
> 
> 

那你需要看下dbcontext是否配置了fluentapi，默认是fluentapi优先级比attribute高

**Comment by xuejmnet** [comment]
![image](https://user-images.githubusercontent.com/18061232/156904418-a854322f-4d66-4aee-ac9d-14495490b3e0.png)

![image](https://user-images.githubusercontent.com/18061232/156904423-2105a1e3-5b95-48ae-a048-6cd9ed7a4635.png)

mysql dbcontext里面我这边配置了map映射关系优先级大于attribute所以还是我配置的，你只需要注册掉用你的外加dbset即可，efcore这两种都是支持的

**Comment by shaosu** [comment]
对了, 删掉就好了
