### ISSUE TITLE
支持多参数构造函数的Dbcontext及手动事务

### ISSUE THREAD

**Issue by Jiayg** [dotnetcore/sharding-core#133]
期待支持多参构造函数的Dbcontext，及手动事务控制
![image](https://user-images.githubusercontent.com/32700982/161372414-1881c7d8-372d-4c88-b47b-34e7c53ba6ce.png)

**Comment by xuejmnet** [comment]
多构造函数参数我这边应该会尽快支持,但是这个构造函数内部使用Database方法可能没办法支持,会让模型提前加载

**Comment by xuejmnet** [comment]
![image](https://user-images.githubusercontent.com/18061232/161418956-80a2da20-07b8-4bc7-ac8a-dc79430fb42c.png)


![image](https://user-images.githubusercontent.com/18061232/161418969-b381a425-2d54-4544-9c1f-56dcc55c3309.png)

**Comment by xuejmnet** [comment]
@Jiayg 更新到最新版本x.4.2.7后如图新建一个dbcontextcreator然后替换掉系统的即可,不过目前构造函数还是不支持database的方法使用

**Comment by xuejmnet** [comment]
database的方法除了事务是支持的外其余可能需要后续支持一下，希望理解

**Comment by Jiayg** [comment]
感谢作者大大及时响应
