### ISSUE TITLE
按需自动建分表

### ISSUE THREAD

**Issue by Im-Kevin** [dotnetcore/sharding-core#147]
我现在有个需求,需要按小时建表,但是又不是说建满24小时,大概其中有10个小时是有数据的,其他时间都是没数据的,所有想在新增的时候处理如果没有表则建表,查询的时候就直接跳过

**Comment by xuejmnet** [comment]
可以的我晚上写一个路由，大概是不是分表按小时后缀，没表创建表，查询跳过什么意思不太清楚什么意思

**Comment by xuejmnet** [comment]
@Im-Kevin 再说下你是mysql还是sqlserver

**Comment by Im-Kevin** [comment]
mysql

**Comment by Im-Kevin** [comment]
就比如我查询9号10号的数据,那么每天10个小时有数据,就是只有20个表,剩下28个小时都是没有对应的表的,那么实际查询应该只是查询了20个表

**Comment by Im-Kevin** [comment]
我们这个只有白天才有数据的,晚上是不会有数据插入的

**Comment by Im-Kevin** [comment]
这种如果创建那28个空表,查询效率就会受到一定的影响

**Comment by xuejmnet** [comment]
可以的

**Comment by Im-Kevin** [comment]
好的,感谢

**Comment by xuejmnet** [comment]
这边建议是升级到新版本就版本建表是阻塞的并且有点小bug

**Comment by Im-Kevin** [comment]
好的,新版本建表不阻塞?那其他数据怎么办

**Comment by Im-Kevin** [comment]
不是很理解

**Comment by xuejmnet** [comment]
原先是这样的，首先efcore没有提供创建指定表的功能，只是提供了创建所有表的功能，但如果已存在就会报错，原先的处理是先获取当前efcore的模型缓存锁，然后把所有模型都删除掉只要我需要创建表的模型，然后创建完表后把整个模型删除，不然当前efcore模型只有一张表了。现在是创建dbcontext然后这个dbcontext的模型不写入模型缓存，也就是说不需要lock模型锁，然后和上述一样移除掉别的表剩一张我要的模型然后建表，因为模型独立不缓存所以不会影响别的dbcpntext下的模型自然而然不需要lock所以是无锁

**Comment by Im-Kevin** [comment]
明白了,感谢解惑

**Comment by xuejmnet** [comment]
原先是操作全局模型，lock，移除所有模型保留一个模型，调用创建所有表的方法，移除模型，释放锁


现在是独立创建dbcontext使用独立模型，然后设置模型不需要缓存，移除模型保留一个，创建所有表，释放dbcontext就可以了因为独立模型不会缓存

**Comment by Im-Kevin** [comment]
嗯

**Comment by xuejmnet** [comment]
@Im-Kevin 源码已经上传 
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/18061232/167638489-f1d11ba7-cd66-44b9-809e-30b20184b438.png">

**Comment by xuejmnet** [comment]
Sample.AutoCreateIfPersent,通过对路由值的获取进行判断是否需要创建表,来达到功能实现

**Comment by xuejmnet** [comment]
RouteWithValue这个路由方法是插入和修改都会经过的方法,所以在这边判断最合适

**Comment by xuejmnet** [comment]
![image](https://user-images.githubusercontent.com/18061232/167646559-2429ced9-58ad-4381-a4b4-c95a90a4c167.png)

我看了下之前我写的多字段分表你使用的这个雪花id解析这边获取当月第一天用了datetime.now其实是不正确的应该用雪花id解析出来的时间而不是datetime.now虽然大部分情况下都不会有问题但是极限下会有问题

**Comment by xuejmnet** [comment]
@Im-Kevin 不知道这个路由是不是你要的

**Comment by xuejmnet** [comment]
这个是分表下是这样的,如果你是分表+分库的话最好参考 [创建数据库](https://github.com/dotnetcore/sharding-core/blob/58ee2a7ba379b96e01815c701a5d12ef53a26430/src/ShardingCore/VirtualRoutes/Abstractions/AbstractShardingAutoCreateOperatorVirtualTableRoute.cs#L64)

**Comment by Im-Kevin** [comment]
好的,我看看先

**Comment by Im-Kevin** [comment]
大佬,问你一个跟这个项目没关的问题,有没有什么工具可以实时监控并发是否已经超出服务器的能力了

**Comment by xuejmnet** [comment]
这个只能靠监控工具,但是我对这方面相对研究的很少所以可能帮不了你

**Comment by Im-Kevin** [comment]
好的,那我再想想

**Comment by xuejmnet** [comment]
![image](https://user-images.githubusercontent.com/18061232/168778995-286c41e9-6f39-4367-bdbb-af782a6469b5.png)

**Comment by Im-Kevin** [comment]
好的,谢谢

**Comment by xuejmnet** [comment]
x.6版本实现更加精简

**Comment by Im-Kevin** [comment]
好的
