### ISSUE TITLE
关于分库且分表时，codefirst迁移的问题

### ISSUE THREAD

**Issue by dodu2014** [dotnetcore/sharding-core#161]
首先很赞同shardingcore的性能，及其在配置和使用中零业务代码入侵的优点。大赞  ❤️💕👍👍👍

在使用过程中遇到这个问题，如下：

## 环境：

efcore 6.0.5
Npgsql.EntityFrameworkCore.PostgreSQL 6.0.4
shardingcore 6.5.0.6

## 需求场景：

分库且同时分表
codefirst，迁移可维护
生产环境可自动完成迁移（包括分库）

## 描述：

由于分库时，可能存在多个库，想通过自动迁移完成主库和分库的更新，现在貌似暂时不支持，只有初始化迁移时候，通过配置 CreateShardingTableOnStart = true 可以完成分库中相关entity的表的初始化（且这样做会和ef的迁移造成冲突，在主库的迁移环节，会提示未分片表已经存在），虽然可以通过 ef migrations script 生成对应的sql脚本，用来手动更新分库表结构，如果分库多时，需要每个库都要应用更新，且分库无迁移历史，没法很直观的看到分库的维护情况，如果那个分库漏掉，程序运行时会提示异常，和主库不同步，所以需要自己手动维护一份所有分库的维护记录，总感觉有些违背efcore的设计理念，希望可以得到改善。

## 其他

动态分库的示例 😊😊

**Comment by dodu2014** [comment]
暂时的做法时通过 script 生产sql脚本，来完成分库的维护 😊

**Comment by xuejmnet** [comment]
x.6.x.x预览版本以支持分片情况下的迁移,并且优化了迁移表使用的线程并发数由原先的串行改成了并行,并且新增补充表，会对datasource分别进行扫描是否缺少表(也是并行执行)

**Comment by dodu2014** [comment]
好的，太棒了，辛苦了 ~~
我正在看升级指南，非常感谢！！
