### ISSUE TITLE
能否更新AbpVNext的DEMO

### ISSUE THREAD

**Issue by chaoyi996** [dotnetcore/sharding-core#178]
[sharding-core](https://github.com/dotnetcore/sharding-core)更新啦，Abp的例子有点旧，能否麻烦更新一下

**Comment by xuejmnet** [comment]
@chaoyi996 https://www.cnblogs.com/xuejiaming/p/16450663.html 看这篇文章 文末有abpvnext的demo

**Comment by xuejmnet** [comment]
给您带来的不便深表歉意

**Comment by chaoyi996** [comment]
您客气了，我拜读一下

**Comment by xuejmnet** [comment]
使用shardingcore6建议查看下文档有些变化

**Comment by xuejmnet** [comment]
@chaoyi996 https://xuejm.gitee.io/sharding-core-doc/guide-upgrade-5-6/ 5升级到6

**Comment by xuejmnet** [comment]
看不到文档就ctrl+shift+r刷新下

**Comment by xuejmnet** [comment]
设计上更加合理并且无需start了，没有全局静态那种设计了更加优雅实现上

**Comment by 867824092** [comment]
我滴妈呀！！！ 兼职是保姆级别的教程了 顶顶顶！

**Comment by xuejmnet** [comment]
> 我滴妈呀！！！ 兼职是保姆级别的教程了 顶顶顶！

尴尬了,我的文档惨不忍睹太懒了一般博客写了文档老是忘掉
