### ISSUE TITLE
可否在自动分表是通过调用存储过程创建分表？

### ISSUE THREAD

**Issue by 867824092** [dotnetcore/sharding-core#184]
您好！ 咨询一些问题，可否在自动创建分表时通过自定义方式创建呢？ 目前生产环境是通过存储过程中创建的 牵扯到分区规则索引名称一些细节，另外 我拓展了AbstractTableEnsureManager（此功能是缓存已存在的分表吗，如果我通过自定义方式创建，那么该功能中所存储的分表名称是否会自动更新呢）

**Comment by xuejmnet** [comment]
@867824092 可以的，你是系统默认的时间分片吗？如果是的话重写系统默认路由的executeasync方法，把里面的tablecreator方法移除掉就可以了

**Comment by xuejmnet** [comment]
https://github.com/dotnetcore/sharding-core/blob/36d8709efeb1f44ecdfecb18783626f8661d352a/src/ShardingCore/VirtualRoutes/Abstractions/AbstractShardingAutoCreateOperatorVirtualTableRoute.cs#L148

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/18061232/185162417-2f6a2acf-571e-4238-ba9c-a79f6a042d52.png">

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/18061232/185162554-a85ee1ed-f401-4afc-a782-20d36c640fc0.png">

**Comment by xuejmnet** [comment]
AbstractTableEnsureManager这个只是为了启动的时候补偿表功能会判断是否有分片表需要补偿，如果有那么补偿的时候会快一点因为内存可以直接知晓哪些表不需要补偿了，如果没有这个AbstractTableEnsureManager那么所有的分片表都要尝试一遍，表过多会变得很慢

**Comment by 867824092** [comment]
> @867824092 可以的，你是系统默认的时间分片吗？如果是的话重写系统默认路由的executeasync方法，把里面的tablecreator方法移除掉就可以了

好的。谢谢您的解答。 是时间分片，我测验下看能否通过定时任务通过自定义方式去调用存储过程创建分表

**Comment by xuejmnet** [comment]
@867824092 executeasync是两步第一步对路由里面添加分片后缀第二步创建表，所以你只要保留第一步即可

**Comment by xuejmnet** [comment]
@867824092 抱歉我看了一下appendtail不是虚方法可能重写会有点问题我后续发布一个版本您看可否

**Comment by 867824092** [comment]
> @867824092 抱歉我看了一下appendtail不是虚方法可能重写会有点问题我后续发布一个版本您看可否

![image](https://user-images.githubusercontent.com/49057777/185266207-b3d9e31a-b1ce-451e-8746-998e7814d252.png)
是这个方法吗？

**Comment by xuejmnet** [comment]
@867824092 我看错了我看错了.....就按我昨天说的就好了直接吧exwcuteasync重写然后创建表的不要

**Comment by 867824092** [comment]
> @867824092 我看错了我看错了.....就按我昨天说的就好了直接吧exwcuteasync重写然后创建表的不要

好的，正在测验。

**Comment by xuejmnet** [comment]
@867824092 早上脑子有点紧😵‍💫 appendtail不需要重写主要是public即可

**Comment by xuejmnet** [comment]
校验的话看下文档里面的路由下的默认路由里面有些着定时执行的时间你把系统时间调整到那个时间点前30秒即可

**Comment by 867824092** [comment]
> 校验的话看下文档里面的路由下的默认路由里面有些着定时执行的时间你把系统时间调整到那个时间点前30秒即可

好的

**Comment by xuejmnet** [comment]
@867824092 既然你的表都是db创建的那么你启动的时候补偿表操作也不需要了没用了如果加了补偿也会创建表

**Comment by xuejmnet** [comment]
UseAutoShardingCreate();这个是创建定时任务需要保留，重写路由里面的任务执行方法即可。
            UseAutoTryCompensateTable();这个是补偿表的方法你那边就不需要了你是自己脚本生成的

**Comment by 867824092** [comment]
请问下，在开启定时任务时，启动报错，容器中是有当前对象的
An exception was thrown while activating λ:ShardingCore.Core.RuntimeContexts.IShardingRuntimeContext.：ArgumentNullException: Value cannot be null. Arg_ParamName_Name
![image](https://user-images.githubusercontent.com/49057777/185268939-578829fa-a293-44a6-9b94-2b0a5f41ad78.png)

**Comment by xuejmnet** [comment]
具体堆栈信息有吗

**Comment by 867824092** [comment]
> 具体堆栈信息有吗

Autofac.Core.DependencyResolutionException
  HResult=0x80131500
  Message=An exception was thrown while activating λ:ShardingCore.Core.RuntimeContexts.IShardingRuntimeContext.
  Source=Autofac
  StackTrace:
   在 Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   在 Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   在 Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   在 Autofac.Core.Resolving.Middleware.SharingMiddleware.<>c__DisplayClass5_0.<Execute>b__0()
   在 Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)
   在 Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid primaryId, Nullable`1 qualifyingId, Func`1 creator)
   在 Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   在 Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   在 Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   在 Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   在 Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   在 Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   在 Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   在 Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   在 Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   在 Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   在 Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   在 ShardingCore.ShardingCoreExtension.UseAutoShardingCreate(IServiceProvider serviceProvider)
   在 ZKGT.DataConsumptionService.EntityFrameworkCore.EfCoreModule.OnPostApplicationInitialization(ApplicationInitializationContext context) 在 E:\Project\SatellitePositioningSecurityServicePlatform\zkgt.dataconsumptionservice\src\ZKGT.DataConsumptionService.Ado\EntityFrameworkCore\EfCoreModule.cs 中: 第 58 行
   在 Volo.Abp.Modularity.AbpModule.OnPostApplicationInitializationAsync(ApplicationInitializationContext context)
   在 Volo.Abp.Modularity.OnPostApplicationInitializationModuleLifecycleContributor.<InitializeAsync>d__0.MoveNext()

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]

内部异常 1:
ArgumentNullException: Value cannot be null. Arg_ParamName_Name

**Comment by xuejmnet** [comment]
你是abpvnext还是abpzero

**Comment by 867824092** [comment]
当前ShardingCore 包版本 6.6.0.29 ，是abp vnext

**Comment by xuejmnet** [comment]
contexy.serverprovider.getservice<ishardingruntimecontext>可以获取吗

**Comment by 867824092** [comment]
获取不到，错误一致

**Comment by xuejmnet** [comment]
context.services.addshardingconfigure的容器和下面post的context的容器一致吗，我感觉是不一致导致的

**Comment by xuejmnet** [comment]
autofac接管的吗

**Comment by 867824092** [comment]
> autofac接管的吗

稍等下哈

**Comment by xuejmnet** [comment]
efcore版本对吗，efcore5用5.6.x.x的shardingcore如果是efcore6才用6.6.x.x的

**Comment by xuejmnet** [comment]
efcore模块能截图一个大图给我看看吗

**Comment by 867824092** [comment]
![image](https://user-images.githubusercontent.com/49057777/185273120-83deb759-83ef-4f67-b3ed-61d93f180223.png)
下面是Module中的代码
 [DependsOn(
     typeof(AbpEntityFrameworkCoreOracleModule))]
    public class EfCoreModule : AbpModule {
        public static readonly ILoggerFactory efLogger = LoggerFactory.Create(builder => {
            builder.AddFilter((category, level) => category == DbLoggerCategory.Database.Command.Name && level == LogLevel.Information).AddConsole();
        });
        public override void ConfigureServices(ServiceConfigurationContext context) {
            context.Services.AddAbpDbContext<VehicleGpsDbContext>(options => {
                /* Remove "includeAllEntities: true" to create
                 * default repositories only for aggregate roots */
                options.AddDefaultRepositories(false);
                options.AddRepository<VehicleGps, VehicleGpsRepository>();
            });

            Configure<AbpDbContextOptions>(options => {
                /* The main point to change your DBMS.
                 * See also VehicleDispatchMigrationsDbContextFactory for EF Core tooling. */
                options.UseOracle();
                options.Configure<VehicleGpsDbContext>(innerContext => innerContext.DbContextOptions.UseDefaultSharding<VehicleGpsDbContext>(innerContext.ServiceProvider));
            });
            var configuration = context.Services.GetConfiguration();
            Configure<EFCoreShardingOptions>(configuration);//efCore分表配置
            context.Services.AddShardingConfigure<VehicleGpsDbContext>()
                            .UseRouteConfig(op => {
                                op.AddShardingTableRoute<VehicleGpsVirtualTableRoute>();
                            })
                            .UseConfig(op => {
                                op.UseShardingQuery((conStr, builder) => {
                                    builder.UseOracle(conStr).UseLoggerFactory(efLogger);
                                });
                                op.UseShardingTransaction((connection, builder) => {
                                    builder.UseOracle(connection).UseLoggerFactory(efLogger);
                                });
                                op.AddDefaultDataSource("default", configuration.GetConnectionString("Default"));
                            }).ReplaceService<ITableEnsureManager, OracleTableEnsureManager>().AddShardingCore();
        }

        public override void OnPostApplicationInitialization(ApplicationInitializationContext context) {
           var rc = context.ServiceProvider.GetRequiredService<IShardingRuntimeContext>();
            //context.ServiceProvider.UseAutoShardingCreate();
        }

**Comment by xuejmnet** [comment]
![image](https://user-images.githubusercontent.com/18061232/185273516-fb48e857-4eae-4f11-b386-169cf107ac97.jpeg) 看了半天好像就这个不一样

**Comment by xuejmnet** [comment]
实在不行的话我下午给你远程看看可以吗

**Comment by 867824092** [comment]
好的，您先忙，我在多尝试尝试

**Comment by 867824092** [comment]
:joy: 找到问题了，在扩展GetCronExpressions 自定义Options注入中获取到是个NUll 引发了问题！ 太大意了..

**Comment by xuejmnet** [comment]
好的解决了就好

**Comment by 867824092** [comment]
> 好的解决了就好
在复写AbstractSimpleShardingMonthKeyDateTimeVirtualTableRoute中GetCronExpressions()方法时，想要通过IOptions<EFCoreShardingOptions>获取对应的配置，RouteShardingProvider.GetRequiredService<IOptions<EFCoreShardingOptions>>() 获取到的对象中属性都是null
![image](https://user-images.githubusercontent.com/49057777/185307512-1ba69682-e82f-4a1a-9bd6-f6c93375ef27.png)

但是在外部的ServerProvider就能获取到
![image](https://user-images.githubusercontent.com/49057777/185307617-dd2ba1fb-9a5a-4ee0-a916-f147641d1b81.png)

**Comment by xuejmnet** [comment]
@867824092 构造函数注入即可，因为getcronexpression是在初始化前，初始化前还不能通过shardingprovider获取

**Comment by xuejmnet** [comment]
这个还真不好弄你试试构造函数注入看看

**Comment by xuejmnet** [comment]
getcronexpression会在初始化完成前被调用所以sharsingprovider那个时候可能还无法用

**Comment by 867824092** [comment]
![image](https://user-images.githubusercontent.com/49057777/185322906-59ebc0d5-b6ad-4a76-9645-53c7c41a333f.png)
貌似也不行

> @867824092 构造函数注入即可，因为getcronexpression是在初始化前，初始化前还不能通过shardingprovider获取

**Comment by xuejmnet** [comment]
@867824092 很奇怪原则上来说是樱花可以获取到的
你试试不用ioptions这个泛型呢
直接获取iconfiguration可以获取到吗

**Comment by xuejmnet** [comment]
还有一个办法你可以注入到shardingcore内部的servicecollection，在addshardingcore前可以通过addservicesconfigure委托注入到shardingcore内部

**Comment by 867824092** [comment]
> 还有一个办法你可以注入到shardingcore内部的servicecollection，在addshardingcore前可以通过addservicesconfigure委托注入到shardingcore内部

这种方式可以了，然后我取消外部的特定Options注入。在外部程序模块加载时获取该Options值就是null了，有点眯 :joy: ，ShardingCore的ServiceCollection也是外部ServiceCollection引用传递，感觉两个ServiceCollection指向地址又不一样了

**Comment by xuejmnet** [comment]
这两个本来就不一样的，默认shardingcore优先获取内部的servicecollection，获取不到会获取外部的iserviceprovider但是不知道你那边为什么不可以

**Comment by xuejmnet** [comment]
实在不行就用实例的方式注入在外部通过iconfiguration创建好efcoreoptions然后注入到应用程序的容器里面内部还没有内部在注册一遍

**Comment by xuejmnet** [comment]
具体原因我晚上看看

**Comment by xuejmnet** [comment]
你不要用configure注入用实例注入就好了，应该是ioptions注入导致的问题

**Comment by xuejmnet** [comment]
原理就是先getservice如果为null那么通过应用的容器获取，ioptions一定能获取到不为null所以就不会去获取应用容器的了

**Comment by 867824092** [comment]
:hugs:  本地环境运行正常， 感谢老板的耐心答疑， 待我放到测试环境跑一俩月 :blush:
