### ISSUE TITLE
AbstractShardingAbpDbContext继承AbpDbContext后LazyServiceProvider属性未注册上,显示值为null

### ISSUE THREAD

**Issue by 867824092** [dotnetcore/sharding-core#197]
![image](https://user-images.githubusercontent.com/49057777/194792962-05e27af4-ad6c-447e-aaf4-40ea39e0e71d.png)

![image](https://user-images.githubusercontent.com/49057777/194792940-6cc97322-ed2e-40c0-b5de-8b339a3594e0.png)

**Comment by xuejmnet** [comment]
@867824092  https://github.com/dotnetcore/sharding-core/blob/860e6dd4cbb0bd2ea4a6bfdede4f6858c2606544/samples/Samples.AbpSharding/AbstractShardingAbpDbContext.cs#L90

重写的dbcontext抽象类请查看这个demo

**Comment by xuejmnet** [comment]
@867824092  https://github.com/xuejmnet/AbpVNextShardingTodoApp这是abp的demo

**Comment by 867824092** [comment]
@xuejmnet  我下载来示例Demo，运行结果也是显示为null
![image](https://user-images.githubusercontent.com/49057777/194794362-4114b44f-8b18-40cc-99a2-36c582057741.png)

**Comment by xuejmnet** [comment]
@867824092 不太懂你说的你是在哪边断点他是null,因为abpvnext集成shardingcore一直是好的，会不会是他本来就是null后续它会自动给他赋值呢,或者你把你断点的地方发一下，或者程序运行一下呢是否有报错

**Comment by xuejmnet** [comment]
@867824092 虽然我不用abp但是据我所知abp创建dbcontext的时候就是null的在new完dbcontext后才会对其进行赋值

**Comment by 867824092** [comment]
抱歉,回复慢了些,我重写了OnConfiguring方法，需要获取容器中的一些信息，我看了下Abp的源码AbpDbContext中的LazyServiceProvider应该是属性注入进来的,AbpVnext中容器替换为Autofac的源码部分
![image](https://user-images.githubusercontent.com/49057777/194808943-b48a2ecc-6daf-426c-be05-9fd958dad0e4.png)
以下是两种对比：
示例一：直接继承AbpDbContext，在进入OnConfiguring时可以获取到属性注入的base.LazyServiceProvider
![image](https://user-images.githubusercontent.com/49057777/194809055-95e28695-23ec-4994-82c0-47b128449fe3.png)
示例二：采用ShardingCore分表策略，编写AbstractShardingAbpDbContext继承AbpDbContext，在进入OnConfiguring时未获取到对象值
![image](https://user-images.githubusercontent.com/49057777/194816265-a61dfb6a-7ed3-4110-94a4-1c00e053647b.png)
这样会导致后续的领域事件无法执行成功,因为有一些属性依赖是通过LazyServiceProvider去解析的。

**Comment by xuejmnet** [comment]
@867824092 建议不要再OnConfiguring上进行处理,最好直接在startup那边处理builder,至于领域事件你放心都是可以的已经有很多abp的测试过了几乎是比较完美的
![image](https://user-images.githubusercontent.com/18061232/194817353-53583202-978c-442b-b0fd-f20743328916.png)

**Comment by xuejmnet** [comment]
这个应该是加载顺序的原因导致的,你可以看看整个dbcontext获取到了是否LazyServicePrivder还是null,这边很多用abp的小伙伴领域事件什么都是支持的所以应该不存在LazyServiceprovider为null,只是ShardingCore因为需要对IRouteTail字段进行赋值,赋值完成后需要对DbContext进行Model的整个模型的冻结确定所以会在createDbContext后直接调用导致OnConfiguring会先执行然后再抽象基类里面还未赋值的情况

**Comment by xuejmnet** [comment]
这是TodoApp的demo的注入 ：)
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/18061232/194818028-3a183ba8-425b-4924-bac3-a8f19025e15d.png">

**Comment by 867824092** [comment]
ok  感谢老板答疑 :smile: 我得在研究研究源码了.. :flushed: 有点懵了..

**Comment by xuejmnet** [comment]
因为架构问题ShardingCore是一个ShellDbContext带多个ExecutorDbContext,但是因为这两个都是同一个Class所以在DbContext内部处理需要分清楚哪个是Shell哪个是executor,这样的好处是对外就是一个dbcontext，但是对内需要通过抽象类的构造函数返回值进行判断到底是否是shell，shell是不会进行执行的只是为了包装executordbcontext 😄

**Comment by xuejmnet** [comment]
@867824092 源码的入口是`ShardingQueryCompiler`这个类，这个类是作用于iqueryable拦截解析的

**Comment by 867824092** [comment]
:ok_hand:  感谢老板耐心指导， 我在整个demo试试去
