### ISSUE TITLE
db context model is inited before RouteTail set value

### ISSUE THREAD

**Issue by liugt34** [dotnetcore/sharding-core#198]
说是在路由设置值之前初始化了，不晓得怎么改， 官方文档也没找到设置的地方，求大神指点！
public static class DatabaseConfig
    {
        public static void **AddDatabaseConfiguration**(this IServiceCollection services, IConfiguration configuration)
        {
            if (services == null) throw new ArgumentNullException(nameof(services));

            services.AddShardingDbContext<EquinoxContext>()
                .UseRouteConfig(op =>
                {
                    op.AddShardingTableRoute<CustomerVirtualTableRoute>();

                })
                .UseConfig(op =>
                {
                    //当无法获取路由时会返回默认值而不是报错
                    op.ThrowIfQueryRouteNotMatch = false;
                    //忽略建表错误compensate table和table creator
                    op.IgnoreCreateTableError = true;
                    //迁移时使用的并行线程数(分库有效)defaultShardingDbContext.Database.Migrate()
                    op.MigrationParallelCount = Environment.ProcessorCount;
                    //补偿表创建并行线程数 调用UseAutoTryCompensateTable有效
                    op.CompensateTableParallelCount = Environment.ProcessorCount;
                    //最大连接数限制
                    op.MaxQueryConnectionsLimit = Environment.ProcessorCount;
                    //链接模式系统默认
                    op.ConnectionMode = ConnectionModeEnum.SYSTEM_AUTO;
                    //如何通过字符串查询创建DbContext
                    op.UseShardingQuery((conStr, builder) =>
                    {
                        builder.UseSqlServer(conStr).UseLoggerFactory(efLogger);
                    });
                    //如何通过事务创建DbContext
                    op.UseShardingTransaction((connection, builder) =>
                    {
                        builder.UseSqlServer(connection).UseLoggerFactory(efLogger);
                    });
                    //添加默认数据源
                    op.AddDefaultDataSource("DefaultConnection", "Data Source=.\\SQLEXPRESS; Database=Equinox; User ID=sa;Password=P@ssw0rd;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False");
                    //添加额外数据源
                    //op.AddExtraDataSource(sp =>
                    //{
                    //    return new Dictionary<string, string>()
                    //    {
                    //        { "B", "Data Source=localhost;Initial Catalog=ShardingCoreDBB;Integrated Security=True;" },
                    //        { "C", "Data Source=localhost;Initial Catalog=ShardingCoreDBC;Integrated Security=True;" },
                    //    };
                    //});

                    //添加读写分离
                    //op.AddReadWriteSeparation(sp =>
                    //{
                    //    return new Dictionary<string, IEnumerable<string>>()
                    //    {
                    //        {
                    //            "A", new HashSet<string>()
                    //            {
                    //                "Data Source=localhost;Initial Catalog=ShardingCoreDBB;Integrated Security=True;"
                    //            }
                    //        }
                    //    };
                    //}, ReadStrategyEnum.Loop, defaultEnable: false, readConnStringGetStrategy: ReadConnStringGetStrategyEnum.LatestEveryTime);
                })
                .ReplaceService<ITableEnsureManager, SqlServerTableEnsureManager>()
                .AddShardingCore();

            services.AddDbContext<EventStoreSqlContext>(options => options.UseSqlServer(configuration.GetConnectionString("DefaultConnection")));

            services.AddScoped<IUnitOfWork, UnitOfWork>();
        }

        public static void UseShardingCore(this IApplicationBuilder app)
        {
            //启动ShardingCore创建表任务(不调用也可以使用ShardingCore)
            //不调用会导致定时任务不会开启
            app.ApplicationServices.UseAutoShardingCreate();
            //启动进行表补偿(不调用也可以使用ShardingCore)
            app.ApplicationServices.UseAutoTryCompensateTable();
        }

        public static readonly ILoggerFactory efLogger = LoggerFactory.Create(builder =>
        {
            builder.AddFilter((category, level) => category == DbLoggerCategory.Database.Command.Name && level == LogLevel.Information).AddConsole();
        });

    }
}

**Comment by xuejmnet** [comment]
dbcontext构造函数不要访问database或者tracker

**Comment by xuejmnet** [comment]
![image](https://user-images.githubusercontent.com/18061232/195565410-fad80431-a887-4cf7-a693-0a9be7f69967.png)



https://xuejm.gitee.io/sharding-core-doc/important/#版本

**Comment by liugt34** [comment]
谢谢大佬
