### ISSUE TITLE
在虚拟表路由里面使用了AutoCreateTable，但是为啥不起作用呢

### ISSUE THREAD

**Issue by liugt34** [dotnetcore/sharding-core#200]
### 数据配置

```
public class CustomerVirtualTableRoute : AbstractSimpleShardingMonthKeyDateTimeVirtualTableRoute<Customer>
    {
        public override DateTime GetBeginTime()
        {
            return new DateTime(2000, 1, 1);
        }

        //注意一定要配置或者采用接口+标签也是可以的
        public override void Configure(EntityMetadataTableBuilder<Customer> builder)
        {
            builder.ShardingProperty(o => o.BirthDate);
            builder.AutoCreateTable(true);
        }

        public override bool AutoCreateTableByTime()
        {
            return true;
        }
    }
```

### Program.cs里面也添加了
```
            app.ApplicationServices.UseAutoShardingCreate();
            app.ApplicationServices.UseAutoTryCompensateTable();
```

### 初始化数据代码
_**在  context.AddRange(orders) 这一行报的错**_
```
public static class SeedExtensions
    {
        public static void InitSeed(this IApplicationBuilder app)
        {
            using (var serviceScope = app.ApplicationServices.CreateScope())
            {
               var context = serviceScope.ServiceProvider.GetRequiredService<EquinoxContext>();
                if (!context.Set<Customer>().Any())
                {
                    var orders = new List<Customer>(300);
                    var begin = new DateTime(2000, 1, 1);
                    for (int i = 0; i < 300; i++)
                    {
                        var username = $"Test{i.ToString("D3")}";
                        var order = new Customer(Guid.NewGuid(), username, $"{username}@b.com", begin);
                        orders.Add(order);
                        begin = begin.AddDays(i);
                    }

                    context.AddRange(orders);
                    context.SaveChanges();
                }
            }
        }
    }
```

ShardingCore.Exceptions.ShardingCoreException
  HResult=0x80131500
  Message=sharding key route not match Equinox.Domain.Models.Customer -> [BirthDate] -> [2022/12/16 0:00:00] -> sharding key to tail :[202212] ->  all tails ->[200001,200002,200003,200004,200005,200006,200007,200008,200009,200010,200011,200012,200101,200102,200103,200104,200105,200106,200107,200108,200109,200110,200111,200112,200201,200202,200203,200204,200205,200206,200207,200208,200209,200210,200211,200212,200301,200302,200303,200304,200305,200306,200307,200308,200309,200310,200311,200312,200401,200402,200403,200404,200405,200406,200407,200408,200409,200410,200411,200412,200501,200502,200503,200504,200505,200506,200507,200508,200509,200510,200511,200512,200601,200602,200603,200604,200605,200606,200607,200608,200609,200610,200611,200612,200701,200702,200703,200704,200705,200706,200707,200708,200709,200710,200711,200712,200801,200802,200803,200804,200805,200806,200807,200808,200809,200810,200811,200812,200901,200902,200903,200904,200905,200906,200907,200908,200909,200910,200911,200912,201001,201002,201003,201004,201005,201006,201007,201008,201009,201010,201011,201012,201101,201102,201103,201104,201105,201106,201107,201108,201109,201110,201111,201112,201201,201202,201203,201204,201205,201206,201207,201208,201209,201210,201211,201212,201301,201302,201303,201304,201305,201306,201307,201308,201309,201310,201311,201312,201401,201402,201403,201404,201405,201406,201407,201408,201409,201410,201411,201412,201501,201502,201503,201504,201505,201506,201507,201508,201509,201510,201511,201512,201601,201602,201603,201604,201605,201606,201607,201608,201609,201610,201611,201612,201701,201702,201703,201704,201705,201706,201707,201708,201709,201710,201711,201712,201801,201802,201803,201804,201805,201806,201807,201808,201809,201810,201811,201812,201901,201902,201903,201904,201905,201906,201907,201908,201909,201910,201911,201912,202001,202002,202003,202004,202005,202006,202007,202008,202009,202010,202011,202012,202101,202102,202103,202104,202105,202106,202107,202108,202109,202110,202111,202112,202201,202202,202203,202204,202205,202206,202207,202208,202209,202210]
  Source=ShardingCore
  StackTrace:
   在 ShardingCore.Core.VirtualRoutes.TableRoutes.Abstractions.AbstractShardingOperatorVirtualTableRoute`2.RouteWithValue(DataSourceRouteResult dataSourceRouteResult, Object shardingKey)
   在 ShardingCore.Core.VirtualRoutes.TableRoutes.TableRouteManager.RouteTo(Type entityType, DataSourceRouteResult dataSourceRouteResult, ShardingTableRouteConfig tableRouteConfig)
   在 ShardingCore.Core.VirtualRoutes.TableRoutes.TableRouteManager.RouteTo(Type entityType, ShardingTableRouteConfig shardingTableRouteConfig)
   在 ShardingCore.Extensions.VirtualDataBaseExtension.GetTableTail[TEntity](ITableRouteManager tableRouteManager, String dataSourceName, TEntity entity)
   在 ShardingCore.Sharding.ShardingDbContextExecutors.ShardingDbContextExecutor.CreateGenericDbContext[TEntity](TEntity entity)
   在 ShardingCore.Sharding.AbstractShardingDbContext.<AggregateToDic>b__20_0[TEntity](TEntity o)
   在 System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   在 System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   在 System.Linq.GroupedEnumerable`2.GetEnumerator()
   在 System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   在 System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   在 ShardingCore.Sharding.AbstractShardingDbContext.AddRange(IEnumerable`1 entities)
   在 Equinox.Services.Api.SeedExtensions.InitSeed(IApplicationBuilder app) 在 E:\Code\Demo\EquinoxProject2\src\Equinox.Services.Api\SeedExtensions.cs 中: 第 27 行
   在 Program.<Main>$(String[] args) 在 E:\Code\Demo\EquinoxProject2\src\Equinox.Services.Api\Program.cs 中: 第 74 行

**Comment by xuejmnet** [comment]
`AutoCreateTableByTime`的意思是是否会按照时间通过定时任务去创建表,而不是你缺什么创建什么,那样程序会变得很危险,毕竟创建表是根据业务参数来了，不过你想要的我这边也有demo，我想你想要的是插入的时候没有就创建路由是吧直接[看这边](https://github.com/dotnetcore/sharding-core/blob/main/samples/Sample.AutoCreateIfPresent/OrderByHourRoute.cs)
默认的时间路由是定时创建的不是你插入的时候创建的,默认时间路由创建时间可以[查看文档](https://xuejm.gitee.io/sharding-core-doc/sharding-route/default-route/#abstractsimpleshardingdaykeylongvirtualtableroute)

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/18061232/195750455-2db121a2-fd6d-40bc-b555-f7b4af153b0e.png">

**Comment by xuejmnet** [comment]
@liugt34 简单的理解为默认路由为了性能不会再插入的时候判断是否存在表,也不会处理表不纯在的情况,他会提前1分钟或者n分钟在定时任务约定好的时间创建表,比如按天创建默认会在每天23:59:00和第二天00:00:00还有第二天00:01:00这3个时间点创建，不过这个可以自定义的希望你可以理解

**Comment by xuejmnet** [comment]
@liugt34 简单理解为系统默认的路由适合创建时间作为路由条件，创建时间是永远不会出现提前出现的情况

**Comment by liugt34** [comment]
> 

感谢大佬解惑，目前正在迁移之前的代码，还不太熟悉
