### ISSUE TITLE
按月分表后，第一张表已经查到了数据，为何还要遍历其他的所有表呢？

### ISSUE THREAD

**Issue by liugt34** [dotnetcore/sharding-core#202]
如图，按月分表，倒叙查询50条记录，第一张表里面已经满足条件并查询到了所有数据，为何其他的表也要遍历一遍呢？
还是说这个仅仅是打印了日志，实际并没有执行查询？求解

![image](https://user-images.githubusercontent.com/8056013/195797515-427e1f4e-d257-4609-9e13-d0627c4abfea.png)

**Comment by xuejmnet** [comment]
你下意识认为第一张表和order by有关系，但是框架不知道，这么说理解吗。框架的执行架构是你会先配置一个maxconnectionlimit，表示单次查询允许的并行数,默认是processcount，会按照这个并行度去查询，然后流式聚合,如果你希望满足你刚才的需求可以配置https://www.cnblogs.com/xuejiaming/p/15966501.html  https://www.cnblogs.com/xuejiaming/p/15848454.html

**Comment by xuejmnet** [comment]
更多设置可以看我的博客文档也有链接指向博客 : )

**Comment by xuejmnet** [comment]
如果你的分页模型是count+list的组合可以看看这篇文章 https://www.cnblogs.com/xuejiaming/p/15237878.html

**Comment by xuejmnet** [comment]
基本上能做的性能优化都已经提供了配置选项可能

**Comment by xuejmnet** [comment]
假设单表不分库的情况下现在有2022,2021,2020,2019,2018,这4张表然后你设置maxconnectionlimit为3在这种情况下如果没有任何配置那么就会对上述tails进行分组[[2022,2021,2020],[2019,2018]]分成两组，这两组是串行执行，先执行第一个3张表同时并行查询然后streammerge，合成的数据在内存中,然后对第二组进行2张表并发查询streammerge，最后在对这两份内存的数据进行最后一次merge然后返回给用户,所以如果你的maxconnectionlimit设置过小会导致查询时间的拉长，如果设置过大会过分消耗连接数

**Comment by xuejmnet** [comment]
配置顺序查询和熔断就是为了你说的情况2022,2021,2020,2019,2018还是这个例子还是maxconnectionlimit=3，如果配置了熔断那么take=50的情况下并且配置order by顺序[[2022,2021,2020],[2019,2018]]这个分组查询第一次3个聚合就可以进行一次熔断判断就是第一次的3个并发如果大于等于50条结果就不进行下次查询了，当然熔断除了全局配置的maxconnectionlimit还有表达式上也支持
```c#
 var sysUserMods1 = _defaultTableDbContext.Set<SysTest>().UseConnectionMode(1)
                .Select(o => new ssss(){ Id = o.Id, C = _abc.Select.Count(x => x.Id == o.Id) }).ToList();
```
UseConnectionMode设置本次查询的并发度,1表示顺序查询2022,2021,2020,2019,2018这个tails的结果就是[[2022],[2021,][2020],[2019],[2018]]每组一个
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/18061232/195811795-05fac08a-2fd0-4fe9-8d0c-d04425eeac87.png">

**Comment by liugt34** [comment]
> 配置顺序查询和熔断就是为了你说的情况2022,2021,2020,2019,2018还是这个例子还是maxconnectionlimit=3，如果配置了熔断那么take=50的情况下并且配置order by顺序[[2022,2021,2020],[2019,2018]]这个分组查询第一次3个聚合就可以进行一次熔断判断就是第一次的3个并发如果大于等于50条结果就不进行下次查询了，当然熔断除了全局配置的maxconnectionlimit还有表达式上也支持
> 
> ```cs
>  var sysUserMods1 = _defaultTableDbContext.Set<SysTest>().UseConnectionMode(1)
>                 .Select(o => new ssss(){ Id = o.Id, C = _abc.Select.Count(x => x.Id == o.Id) }).ToList();
> ```
> 
> UseConnectionMode设置本次查询的并发度,1表示顺序查询2022,2021,2020,2019,2018这个tails的结果就是[[2022],[2021,][2020],[2019],[2018]]每组一个 <img alt="image" width="1167" src="https://user-images.githubusercontent.com/18061232/195811795-05fac08a-2fd0-4fe9-8d0c-d04425eeac87.png">

非常感谢大神回复，大概能明白了
