### ISSUE TITLE
AbstractShardingDbContext中的Commit方法能不能改成virtual,方便重写？

### ISSUE THREAD

**Issue by liugt34** [dotnetcore/sharding-core#207]
比如我在commit之前需要做一些操作，这样就可以重写AbstractShardingDbContext

...do something
base.Commit();
或者有没有其他的类似前置处理的方法呢？拦截器什么的

![image](https://user-images.githubusercontent.com/8056013/196123751-c17d856e-63bb-47ab-b1ac-fabf8bacbe3d.png)

**Comment by xuejmnet** [comment]
@liugt34 实在抱歉后续可以添加这个改成virtual目前你可以做的方法就是把`AbstractShardingDbContext`自己拷贝一份，因为框架只依赖IShardingDbContext不依赖`AbstractShardingDbContext`这个实现类你可以自己来实现

**Comment by xuejmnet** [comment]
如果你很急的话建议你先自己实现这个类只需要一模一样拷贝一份即可,如果不是很急我下个版本晚上应该可以改成virtual

**Comment by xuejmnet** [comment]
但是我看了你的图片,你不是应该在savechange的时候处理吗为什么是commit的时候？

**Comment by liugt34** [comment]
我搞了一个UnitOfWork，里面有个Commit方法

**Comment by xuejmnet** [comment]
@liugt34 你这个是和我同名了，并不是你说的问题可以通过全名称或者改成commitasync

**Comment by liugt34** [comment]
嗯，好的，谢谢！ O(∩_∩)O
