### ISSUE TITLE
如果表结构发生了变动，如何快速修改所有表的列？

### ISSUE THREAD

**Issue by liugt34** [dotnetcore/sharding-core#211]
问下大神有没有提供工具或者建议？

**Comment by xuejmnet** [comment]
迁移,ShardingCore支持原本的EFCore的迁移功能,只要表名不改变目前来看的迁移都是支持的

**Comment by xuejmnet** [comment]
https://www.cnblogs.com/xuejiaming/p/16450663.html 可以看下这个博客里面有多个框架集成ShardingCore后做的迁移

**Comment by xuejmnet** [comment]
唯一要注意的就是表名的修改目前还不支持,当然是分片表的表名,其他情况和efcore迁移一样，并且支持脚本模式的导出方便生产环境执行

**Comment by xuejmnet** [comment]
如果你不熟悉efcore的迁移可以先使用efcore的原生框架具体文档可以参考这个https://learn.microsoft.com/zh-cn/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli

**Comment by liugt34** [comment]
回复好快，谢谢O(∩_∩)O
