### ISSUE TITLE
补偿表问题

### ISSUE THREAD

**Issue by seeyangy** [dotnetcore/sharding-core#215]
场景：数据库源三个00，01，02；00为数据支持库；01、02数据存储库。数据表Order配置为分库分表，数据源配置为01、02。
现象：自动补偿表时，Order表会生成到00支持库。
不知道是用法问题还是bug?

**Comment by xuejmnet** [comment]
@seeyangy 问下shardingcore版本，路由可以的话发一下，分库路由，你说的情况确实不会，但是我记得我测试过的 ：）

**Comment by seeyangy** [comment]
版本是最新版本6.8.0.2

`public class OrderVirtualDataSourceRoute : AbstractShardingOperatorVirtualDataSourceRoute<Order, string>
    {
        private readonly List<string> _dataSources = new List<string>()
        {
            "01", "02"
        };
        //我们设置区域就是数据库
        public override string ShardingKeyToDataSourceName(object shardingKey)
        {
            var shardingKeyToDataSourceName = shardingKey == "A" ? "01" : "02";// Math.Abs(ShardingCoreHelper.GetStringHashCode(shardingKey?.ToString() ?? string.Empty) % 2).ToString().PadLeft(2, '0');
            return shardingKeyToDataSourceName;
        }

        public override List<string> GetAllDataSourceNames()
        {
            return _dataSources;
        }

        public override bool AddDataSourceName(string dataSourceName)
        {
            if (_dataSources.Any(o => o == dataSourceName))
                return false;
            _dataSources.Add(dataSourceName);
            return true;
        }

        public override Func<string, bool> GetRouteToFilter(string shardingKey, ShardingOperatorEnum shardingOperator)
        {

            var t = ShardingKeyToDataSourceName(shardingKey);
            switch (shardingOperator)
            {
                case ShardingOperatorEnum.Equal: return tail => tail == t;
                default:
                    {
                        return tail => true;
                    }
            }
        }

        public override void Configure(EntityMetadataDataSourceBuilder<Order> builder)
        {
            builder.ShardingProperty(o => o.Area);
        }
    }

public class OrderRoute:AbstractSimpleShardingModKeyStringVirtualTableRoute<Order>
    {
        protected override bool RouteIgnoreDataSource => false;

        public OrderRoute() : base(2, 3)
        {
        }

        public override void Configure(EntityMetadataTableBuilder<Order> builder)
        {
            builder.ShardingProperty(o => o.Id);
        }
    }
`

**Comment by xuejmnet** [comment]
好的我下午看看实在不好意思

**Comment by xuejmnet** [comment]
@seeyangy 实在不好意思您看看6.8.0.4版本应该已经修复了: )

**Comment by xuejmnet** [comment]
@seeyangy 您可以试试看

**Comment by seeyangy** [comment]
可以啦，谢谢。
