### ISSUE TITLE
cache model timeout 

### ISSUE THREAD

**Issue by relay-ty** [dotnetcore/sharding-core#221]
堆栈：
在 ShardingCore.EFCores.ShardingModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   在 Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   在 Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   在 Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   在 Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   在 Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   在 Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   在 Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   在 Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   在 Microsoft.EntityFrameworkCore.DbContext.get_Model()
   在 ShardingCore.Core.DbContextCreator.ActivatorDbContextCreator`1.CreateDbContext(DbContext shellDbContext, ShardingDbContextOptions shardingDbContextOptions)
   在 ShardingCore.Sharding.ShardingDbContextExecutors.DataSourceDbContext.CreateDbContext(IRouteTail routeTail)
   在 ShardingCore.Sharding.ShardingExecutors.MergeQueryCompilerContext.GetQueryCompilerExecutor()
   在 ShardingCore.Sharding.ShardingExecutors.DefaultShardingTrackQueryExecutor.ExecuteAsync[TResult](IQueryCompilerContext queryCompilerContext, CancellationToken cancellationToken)
   在 ShardingCore.Sharding.ShardingExecutors.DefaultShardingCompilerExecutor.ExecuteAsync[TResult](IShardingDbContext shardingDbContext, Expression query, CancellationToken cancellationToken)
   在 ShardingCore.EFCores.ShardingQueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   在 Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   在 Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   在 Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   在 Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.CountAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)

程序集 ShardingCore, Version=7.6.0.7

后台任务  多线程 查询 时问题可复现

**Comment by xuejmnet** [comment]
升级到7.x.0.7设置模型并发锁级别
https://github.com/dotnetcore/sharding-core/blob/9de612b37fe05e23e0ad58591dee8eb3c62d6d9c/test/ShardingCore.Test/Startup.cs#L59

**Comment by xuejmnet** [comment]
@relay-ty 如果tails过多可以适当的增大并发等级然后将单个缓存的size设置为1，efcore默认10240的限制那么最多可以缓存10240个对象模型，或者将等待时间设置大一点
```c#
.UseConfig((sp,o) =>
{
                    o.CacheModelLockConcurrencyLevel = 1024;
                    o.CacheEntrySize = 1;
                    o.ModelCacheLockObjectSeconds = 10;
                    o.CheckShardingKeyValueGenerated = false;
})
```

**Comment by xuejmnet** [comment]
升级到7.x.0.8后可以通过config设置，原先的接口设置已经被移除了

**Comment by relay-ty** [comment]
3Q,问题已经得到解决
