### ISSUE TITLE
能否根据主表的字段分表，同时也把子表的进行对应的分表？

### ISSUE THREAD

**Issue by QianMoXi** [dotnetcore/sharding-core#225]
请问一下，如果有如下两张表Order、OrderDetail（业务场景需求，字段无法固定，运行时也会变动，只能这样设计），能否根据Order表中的UserID或者Time同时对Order表、OrderDetail表进行分表操作。
其中，OrderDetail不会被单独查询，只会join order表来读取数据。
```
    public class Order
    {
        public Guid Id     { get; set; }
        public Guid UserID { get; set; }
        public DateTime Time   { get; set; }
    }

    public class OrderDetail
    {
        public long   Id      { get; set; }
        public Guid   OrderID { get; set; }
        public string Key     { get; set; }
        public string Value   { get; set; }
   }
```

想实现的大概的效果：

查询Order的2022年12月的数据时，假设查询了Order_202212，关联OrderDetail查询时，也直接查询OrderDetail_202212的数据，写入数据时也同理。

看了文档和例子了，但是都没找到相关的说明，不知道能否实现这样的需求。

**Comment by xuejmnet** [comment]
@QianMoXi  可以的但是你的`OrderDetail`需要改造
```c#
 public class OrderDetail
    {
        public long   Id      { get; set; }
        public Guid   OrderID { get; set; }
        public string Key     { get; set; }
        public string Value   { get; set; }
//添加这个字段,然后用这个字段进行分表路由
        public DateTime MainOrderTime   { get; set; }
   }
```
修改配置
```c#
    .UseRouteConfig(o =>
                {
                    o.AddShardingTableRoute<DynamicTableRoute>();
                    o.AddShardingTableRoute<SysUserLogByMonthRoute>();
                    // o.AddShardingTableRoute<SysUserModVirtualTableRoute>();
                    o.AddShardingDataSourceRoute<SysUserModVirtualDataSourceRoute>();
                    o.AddParallelTableGroupNode(new ParallelTableGroupNode(new List<ParallelTableComparerType>()
                    {
                        new ParallelTableComparerType(typeof(SysUserMod)),
                        new ParallelTableComparerType(typeof(SysUserLogByMonth)),
                    }));
                })
```
<img width="936" alt="image" src="https://user-images.githubusercontent.com/18061232/207252266-462e1ef0-d268-486e-8f9a-c45209ea7598.png">

这样可以添加平行表，就是如果你在join查询的时候如果分片对象有且仅有SysUserMod和SlysUseLogByMonth的时候那么tails不会出现笛卡尔积，就是说Order202212 join OrderDetail202212不会出现分片错位的情况,不知道你要的是不是这个

**Comment by xuejmnet** [comment]
这边提供的平行表绑定功能就是当出现分片对象有两个及以上的时候Tail一样的在一起而不是笛卡尔积

**Comment by QianMoXi** [comment]
> @QianMoXi 可以的但是你的`OrderDetail`需要改造
> 
> ```cs
>  public class OrderDetail
>     {
>         public long   Id      { get; set; }
>         public Guid   OrderID { get; set; }
>         public string Key     { get; set; }
>         public string Value   { get; set; }
> //添加这个字段,然后用这个字段进行分表路由
>         public DateTime MainOrderTime   { get; set; }
>    }
> ```
> 
> 修改配置
> 
> ```cs
>     .UseRouteConfig(o =>
>                 {
>                     o.AddShardingTableRoute<DynamicTableRoute>();
>                     o.AddShardingTableRoute<SysUserLogByMonthRoute>();
>                     // o.AddShardingTableRoute<SysUserModVirtualTableRoute>();
>                     o.AddShardingDataSourceRoute<SysUserModVirtualDataSourceRoute>();
>                     o.AddParallelTableGroupNode(new ParallelTableGroupNode(new List<ParallelTableComparerType>()
>                     {
>                         new ParallelTableComparerType(typeof(SysUserMod)),
>                         new ParallelTableComparerType(typeof(SysUserLogByMonth)),
>                     }));
>                 })
> ```
> 
> <img alt="image" width="936" src="https://user-images.githubusercontent.com/18061232/207252266-462e1ef0-d268-486e-8f9a-c45209ea7598.png">
> 
> 这样可以添加平行表，就是如果你在join查询的时候如果分片对象有且仅有SysUserMod和SlysUseLogByMonth的时候那么tails不会出现笛卡尔积，就是说Order202212 join OrderDetail202212不会出现分片错位的情况,不知道你要的是不是这个

谢谢，我试试

**Comment by QianMoXi** [comment]
> 这边提供的平行表绑定功能就是当出现分片对象有两个及以上的时候Tail一样的在一起而不是笛卡尔积

我使用了AddParallelTableGroupNode方法后，还是出现了笛卡尔积的情况：
![image](https://user-images.githubusercontent.com/26250460/207269838-9e0b674f-e7a4-4a3c-b6d8-80feebf8597f.png)

代码如下（net7 + ef core 7）：
![image](https://user-images.githubusercontent.com/26250460/207270805-45147f71-aea4-4d21-ac9d-80309d63a0c3.png)
![image](https://user-images.githubusercontent.com/26250460/207270933-b90ed72c-35e8-47e0-a995-84ea419beb27.png)

Order、OrderDetail的路由表均继承AbstractSimpleShardingMonthKeyDateTimeVirtualTableRoute，配置是完全一样的
![image](https://user-images.githubusercontent.com/26250460/207271916-f59ad4ef-a9c2-4299-8188-845ffc0f6d62.png)


不知是哪里配置有问题？

**Comment by xuejmnet** [comment]
@QianMoXi 好的我看一下当初做好后就一直搁置着我今晚看看

**Comment by xuejmnet** [comment]
@QianMoXi 升级到7.x.0.11应该修复了实在不好意思
