### ISSUE TITLE
很抱歉 一个可能是新手才会出现的问题，我无法找到我的IShardingTable

### ISSUE THREAD

**Issue by Sichongzou** [dotnetcore/sharding-core#246]
我通过Nuget安装了包
这是我实体类的环境
![image](https://github.com/dotnetcore/sharding-core/assets/68594934/884c1277-74e7-4576-af29-39d5c8a65fa9)

我很确定我应该使用这个版本的包 因为
![image](https://github.com/dotnetcore/sharding-core/assets/68594934/15163c6f-aaf4-4e2a-931c-bff002c25a19)

我按照Readme中的步骤，创建一个实体类，让他继承IShardingTable 我并找不到他
![image](https://github.com/dotnetcore/sharding-core/assets/68594934/626f6c83-1db5-4595-bb39-f5ede304c8b1)

zheye这也就导致我无法开展进一步工作，我不知道我哪个步骤出现了问题。

**Comment by xuejmnet** [comment]
抱歉readme里面可能是之前很久前的代码了我等会更新下实在不好意思
具体可以参考文档 https://xuejm.gitee.io/sharding-core-doc/guide/quick-start-aspnetcore/

**Comment by Sichongzou** [comment]
好的好的，非常感谢您的回复
