### ISSUE TITLE
使用已经存在的分表查询出现表不存在

### ISSUE THREAD

**Issue by henrydingchina** [dotnetcore/sharding-core#248]
当我的库里有2022-1月到2023-06月的表，但是我重写了GetBegTime方法返回2020-1月的时候，查询数据出现表不存在的错误，有什么方法可以避免出现这个问题，查询的时候以当前数据库中最小的表开始

**Comment by xuejmnet** [comment]
那你是否应该把begintime改成数据库表的最小那个月份呢既然你说有那么要不就把表补齐要么就以实际为准

**Comment by xuejmnet** [comment]
或者你参考源码案例autoifpresent，里面有如何获取现有数据库表名你自己重写gettails从数据库获取也可以

**Comment by henrydingchina** [comment]
主要原因是因为表不是由我这边去创建和维护的，我只做查询，只有被动去兼容别人的表结构

**Comment by xuejmnet** [comment]
那他改了你程序不是也要重新启动

**Comment by henrydingchina** [comment]
首次部署的时候需要，后面最小的表就固定了，只会向前去创建表，现在就是这套程序都是新部署的，之前给的都是我程序写死的一个默认的时间，导致出现这个表不存在的问题，所以我就想程序自己去获取这个时间就没哟这个问题了。或者有什么更好的方式

**Comment by henrydingchina** [comment]
嗯嗯，感谢回答
