### ISSUE TITLE
分表之后 左联查询和子集合查询数据重复

### ISSUE THREAD

**Issue by Qeezy23** [dotnetcore/sharding-core#253]
很感谢作者的分表工具 基本满足我们大多数的需要 但是还有两种查询 不知道能不能实现

我目前有一个主表和一个子表 已经按天分表 大约分了几十个表了
我还需要做两种查询

一个是包含子表集合的查询

`var result = await _dbContext.Set<Patient>().Select(t => new`
`            {`
`                t.Id,`
`                t.Name,`
`                StudyList = _dbContext.Set<Study>().Where(t1 => t1.PatientId == t.Id).Select(t1 => new`
`                {`
`                    t1.Id,`
`                    t1.Uid`
`                }).ToList()`
`            }).ToListAsync();`
查出来的数据会有重复
![企业微信截图_20230925104919](https://github.com/dotnetcore/sharding-core/assets/79734925/9c0639b4-3ab0-4898-be2c-c82a9916650c)

另外就是左联查询

`            var list = await _dbContext.Set<Patient>()`
`                .GroupJoin(_dbContext.Set<Study>(), patient => patient.Id,`
`                    study => study.PatientId,`
`                    (patient, studyList) => new { patient, studyList })`
`                .SelectMany(t => t.studyList.DefaultIfEmpty(),`
`                    (group, study) => new { group, study })`
`                .Select(t => new`
`                {`
`                    t.group.patient.Id,`
`                    t.group.patient.Name,`
`                    Uid = t.study == null ? null : t.study.Uid`
`                }).ToListAsync();`
同样也是有重复的数据
![111](https://github.com/dotnetcore/sharding-core/assets/79734925/ff3b97d6-7394-46b9-b202-642a74bc5814)

请问怎么样可以在高性能的情况下 实现以上两种查询？谢谢。

**Comment by xuejmnet** [comment]
@Qeezy23 您好非常感谢您的使用，第一种情况是因为sharding-core不支持嵌套对象,所以你可以左连接后查询结果在内存合并,对于数据库而言结果都是一样性能也是一样的知识efcore帮你做了聚合主从关系,第二种情况目前来讲恕我看不出来具体的sql，所以没办法回答,就是建议如果遇到这种情况建议采用平铺的数据结构,而不是嵌套结构作为返回结果,这样sharding-core才可以帮你把数据正确的获取出来,可以的话发一下执行sql我这边看看 ：）

**Comment by xuejmnet** [comment]
@Qeezy23 至于高性能的话建议看下我的博客 https://www.cnblogs.com/xuejiaming/?page=1 里面有对分片的极致优化,当然这些都是符合现实的,如果您对分片也有了解获取会有不少的收货,最主要的还是框架的聚合模型

**Comment by xuejmnet** [comment]
@Qeezy23 如果你是仅分表没有分库,并且必须要这个方法可以使用unionall模式来进行,这样基本上99%的分片都可以支持,默认可以选择不开启  https://github.com/dotnetcore/sharding-core/tree/main/samples/Sample.SqlServer/UnionAllMerge  ：）

**Comment by Qeezy23** [comment]
@xuejmnet 感谢回复
其实第二个就是左联的查询 我换了下面的写法 还是会有重复数据
请问在这个框架下 正确左联要怎么写呢？
![企业微信截图_20230926110152](https://github.com/dotnetcore/sharding-core/assets/79734925/211244b2-2642-4946-ab25-e465b8233e6a)

**Comment by Qeezy23** [comment]
@xuejmnet
目前看要实现我的查询 左联就是最简单的办法了 这个分表工具太强大了 很多功能我都用不上

**Comment by xuejmnet** [comment]
> @xuejmnet 感谢回复 其实第二个就是左联的查询 我换了下面的写法 还是会有重复数据 请问在这个框架下 正确左联要怎么写呢？ ![企业微信截图_20230926110152](https://user-images.githubusercontent.com/79734925/270524304-211244b2-2642-4946-ab25-e465b8233e6a.png)

正确的左连接就是一对多查询,主表会出现在每个子表的数据里面这个是正常的吧,你数据库写左连接也是呀一对多,主表id如果查询出来本来就是在子表的每一条记录上的,所以框架查询也是对的,你自己在内存中group by 即可

**Comment by Qeezy23** [comment]
@xuejmnet 好的 
我试了一下 两个表分别单独查完 再内存组成结构更快些
