### ISSUE TITLE
对分片数据查询时返回指定字段不包含ID的情况下会导致重复

### ISSUE THREAD

**Issue by warcraft007** [dotnetcore/sharding-core#254]
![1](https://github.com/dotnetcore/sharding-core/assets/45378612/57f1b2ff-7ea7-46a1-afaf-c42f11ab74c7)
![2](https://github.com/dotnetcore/sharding-core/assets/45378612/65d41737-ccab-4a6c-8ee1-a0ed8d775350)
![3](https://github.com/dotnetcore/sharding-core/assets/45378612/4062f3c9-54d7-4a91-ae58-c0b0ba1615ee)

实例中测试使用同样的分片表和同样的条件进行查询；
图2中可以看到返回的指定字段（不包含ID）的情况下，数据全是重复的第一条数据；
图3中可以看到返回的所有字段的情况下，数据就没有重复；

**Comment by xuejmnet** [comment]
应该是你的id是guid不能为null,然后查询又是追踪查询导致的,如果使用追踪查询那么id一样的数据会被认为是同一条,你的guid没有赋值又不能为null所以都是000-000-00,就导致了efcore认为是同一个数据库对象,所以不会添加新对象,解决办法有三种:
- 使用AsNoTracking()查询
- Select new ResultEntity ,ResultEntity非数据库对象,可以是dto或者匿名对象
- 查询的时候Select primaryKey
