### ISSUE TITLE
group by 查询多个表提示Value cannot be null

### ISSUE THREAD

**Issue by wodemingzijiaoke** [dotnetcore/sharding-core#257]
使用query.select(q=> q.time).groupby(g=> g).count() Linq报错， Value cannot be null。查询的表有的是没有数据的。但是查单个表是不会报这个错的

**Comment by xuejmnet** [comment]
query.select(q=> q.time).groupby(g=> g.Key).count() 试试这种写法呢,你的问题我这几天看看

**Comment by xuejmnet** [comment]
当然这边也建议你用distinct来代替呢，比如query.select(q=> q.time).distinct().count()

**Comment by xuejmnet** [comment]
group的限制是查询的结果必须包含group时候的key

**Comment by wodemingzijiaoke** [comment]
query.groupby(g=> g.time).select(q=> new{time=q.Key}).count() 这种写法也试过，会报错：[Key] not in type:[Table].
query.select(q=> new { q.time}).distinct().count() 这个是可以的

**Comment by wodemingzijiaoke** [comment]
query.groupby(g=> g.time).select(q=> new{time=q.Key}).count() 这种写法也试过，会报错：[Key] not in type:[Table]
query.select(q=> q.time).distinct().count() 这个会报错
query.select(q=> new { q.time}).distinct().count() 这个是可以的

**Comment by xuejmnet** [comment]
@wodemingzijiaoke 实在不好意思因为分片+group是一种比较复杂的聚合处理,如果您不涉及分库那么可以使用shardingcore的unionmerge 具体代码参考 https://github.com/dotnetcore/sharding-core/tree/main/samples/Sample.SqlServer

**Comment by wodemingzijiaoke** [comment]
好的，我去试下

**Comment by wodemingzijiaoke** [comment]
我用的是mysql8,我在mysql的demo中没有找到关于unionmerge的用法，可以提供下demo吗

**Comment by xuejmnet** [comment]
> 我用的是mysql8,我在mysql的demo中没有找到关于unionmerge的用法，可以提供下demo吗
> 
> 
和sqlserver处理一样就换一下对应的方言生成器就好了
