### ISSUE TITLE
是否可以用两个字段去做路由

### ISSUE THREAD

**Issue by Im-Kevin** [dotnetcore/sharding-core#261]
我想每天生成3个表,然后通过时间找到当天,然后通过另外一个字段取模定位到表,请问该如何实现

**Comment by xuejmnet** [comment]
@Im-Kevin 可以的我的仓库应该有个twopropwerties的demo你看看双字段分片

**Comment by xuejmnet** [comment]
@Im-Kevin https://github.com/xuejmnet/TwoPropertyDemo 这个是双字段分片，至于自动不自动本身就是没有自动一说只是时间分片刚好满足分片规则所以看上去自动本质还是在需要的时候往路由里面加表而已

**Comment by xuejmnet** [comment]
比如table_浙江_00 table_北京_01模型有两个字段来确定分片表，还会有一个组合字段不过不映射到表的

**Comment by Im-Kevin** [comment]
好的,谢谢

**Comment by Im-Kevin** [comment]
我想问下是否可以ShardingProperty里面直接将整个Entity传过去,这样是否有其他影响

**Comment by xuejmnet** [comment]
@Im-Kevin 你where的时候怎么可能是整个对象呢条件肯定是一个值你不能只考虑insert或者update对象这种情况

**Comment by Im-Kevin** [comment]
好的,谢谢
