### ISSUE TITLE
单实例DbContext，插入数据出现主键冲突后，重新赋值DbContext后，插入数据返回成功，但是实际没有插入到数据库中

### ISSUE THREAD

**Issue by jifengmm** [dotnetcore/sharding-core#263]
执行下列插入操作发生主键冲突
DbSet.AddRange(objs);
DbContext.SaveChanges();
在trycache中写入下列代码，目的是为了清除之前add进来的冲突的数据
var contextOptions = new DbContextOptionsBuilder<XXXXDbContext>().Usesqlserver("Data Source=XXXXXXX连接字符串").Options;
DbContext = new XXXXDbContext(contextOptions);
然后就再也插入不了其他数据了，但是DbContext.SaveChanges()返回大于-1的数据

**Comment by jifengmm** [comment]
之前在trycatch中使用DbSet.Remove(objs);来清除add进来的主键冲突数据，但是有时候会清理不掉，所以想用重新初始化DBcontext的方式清除

**Comment by xuejmnet** [comment]
能否发一个最小demo ：）

**Comment by jifengmm** [comment]
通过以下代码解决
catch (Exception ex)
{
    if (ex.Message.Contains("更新条目时出错"))
    {
        DbContext.Dispose();
        var contextOptions = new DbContextOptionsBuilder<KJ95XDbContext>().UseSqlServer().Options;
        DbContext = new KJ95XDbContext(contextOptions);
    }
    throw ex;
}
