### ISSUE TITLE
我有多个库里面的表都需要按年分表，但是只有最后一个库可以自动创建表

### ISSUE THREAD

**Issue by jifengmm** [dotnetcore/sharding-core#264]
这个是代码，感觉是后面的配置把前面的覆盖了，只有最后一个生效
#region 分表配置
//额外添加分片配置
builder.Services.AddShardingDbContext<KJ95XDbContext>()
    .UseRouteConfig(op =>
    {
        op.AddShardingTableRoute<OrderVirtualTableRoute>();

    }).UseConfig(op =>
    {
        op.UseShardingQuery((connStr, builder) =>
        {
            //connStr is delegate input param
            builder.UseSqlServer(connStr);
        });
        op.UseShardingTransaction((connection, builder) =>
        {
            //connection is delegate input param
            builder.UseSqlServer(connection);
        });
        //use your data base connection string
        op.AddDefaultDataSource(Guid.NewGuid().ToString("n"),
            builder.Configuration.GetConnectionString("XXX1DbConnectionString"));
    }).AddShardingCore();

builder.Services.AddShardingDbContext<VentilateDbContext>()
    .UseRouteConfig(op =>
    {
       op.AddShardingTableRoute<XXXVirtualTableRoute>();
    }).UseConfig(op =>
    {
        op.UseShardingQuery((connStr, builder) =>
        {
            //connStr is delegate input param
            builder.UseSqlServer(connStr);
        });
        op.UseShardingTransaction((connection, builder) =>
        {
            //connection is delegate input param
            builder.UseSqlServer(connection);
        });
        //use your data base connection string
        op.AddDefaultDataSource(Guid.NewGuid().ToString("n"),
            builder.Configuration.GetConnectionString("XXX2DbConnectionString"));
    }).AddShardingCore();

**Comment by xuejmnet** [comment]
AddShardingDbContext的泛型DbContext是一样的吗 @jifengmm

**Comment by jifengmm** [comment]
不是一样的
public class XXX1DbContext : AbstractShardingDbContext, IShardingTableDbContextXXX
public class XXX2DbContext : AbstractShardingDbContext, IShardingTableDbContext

**Comment by jifengmm** [comment]
@xuejmnet 不是一样的，然后是两个数据连接字符串

**Comment by jifengmm** [comment]
还想请教一个问题，我两个库里面，有相同名字的表，逻辑一样的，我只建立了一个模型，想通过切换dbcontext达到代码复用的目的，这个怎么实现？

**Comment by jifengmm** [comment]
@xuejmnet 代码怎么给你？通过邮箱还是什么？

**Comment by jifengmm** [comment]
或者有微信可以加一下吗

**Comment by xuejmnet** [comment]
@jifengmm efcore 默认不就是可以的嘛一个模型两种映射，代码的话github微信qq都可以,微信号：imxuejiaming

**Comment by jifengmm** [comment]
@xuejmnet 加你了，通过一下

**Comment by jifengmm** [comment]
经过大佬的指点，通过以下代码解决
var shardingRuntimeContexts = app.Services.GetRequiredService<IEnumerable<IShardingRuntimeContext>>();
foreach (var shardingRuntimeContext in shardingRuntimeContexts)
{
    shardingRuntimeContext.UseAutoTryCompensateTable();
}

//app.Services.UseAutoTryCompensateTable();
