### ISSUE TITLE
支持添加字段吗

### ISSUE THREAD

**Issue by henrydingchina** [dotnetcore/sharding-core#268]
### 问题
* 我在使用这个库进行分库分表操作的时候，随着业务的增加更新，可能需要对表中的字段进行了调整，
* 比如我原始分了3张月表，里面只有字段id，name，后面我新增了字段type，组件会自动帮我创建字段吗？

**Comment by xuejmnet** [comment]
@henrydingchina 如果你有迁移文件使用code-first的话那么是支持得,如果没用code-first,可以在添加字段前初始化一份迁移文件然后添加字段也是支持的,如果不放心可以通过生成迁移脚本来查看是否生成了
