### ISSUE TITLE
根据时间分表：未获取到设置的时间值

### ISSUE THREAD

**Issue by gainorloss** [dotnetcore/sharding-core#271]
添加数据：我的某个日志表需要根据年份去分表，其中的路由字段创建时间是在 **_SavingChanges_** 事件中处理给值的，报错是提示取到的这个字段为没赋值之前的默认值，请问下，我这个应该如何调整才能兼容

**Comment by xuejmnet** [comment]
@gainorloss 啥叫没赋值之前的默认值,你是新增的话不是对象里面会给比如createTime赋值吗,你是通过拦截器来实现的?还是什么.你的框架是abp还是纯aspnetcore自己的

**Comment by gainorloss** [comment]
你好我是利用efcore的 保存之前的事件 事件名为 _SavingChanges_

**Comment by xuejmnet** [comment]
@gainorloss 
你需要把拦截器注册到sharding-core提供的配置那边
<img width="1204" alt="image" src="https://github.com/user-attachments/assets/9d680978-7fa4-45d6-8c89-d42e1e04aa89">
`UseShardingTransaction`

**Comment by gainorloss** [comment]
你好，值其实在最终保存的时候是获取到了，看报错应该是路由在寻表的时候没有正确获取到创建时间，
1. 我这边设置的是一个事件注册，事件注册是在构造函数完成 不是一个拦截器
2. 假设我这边用拦截器做字段审核填充，我在构造函数里面完成了拦截器添加，这边在注册sharding-core的时候还需要再添加一次吗
问题像是取路由键的时机问题，这边是在什么时候获取的路由键呢

**Comment by xuejmnet** [comment]
@gainorloss addAsync的时候会获取stateManger这个时候就会根据路由键获取正确的dbcontext的正确的stateManager所以可能拦截器里面不能设置路由键他会比一开始选择正确的dbcontext要前

先根据路由键获取正确的dbcontext,然后才会在dbcontext去执行正确的拦截器

**Comment by xuejmnet** [comment]
所以除了路由键其他的值都可以通过拦截器设置

**Comment by gainorloss** [comment]
好的，谢谢，我研究下
