### ISSUE TITLE
SqlServer 创建Sequence 导致建库时分表无法创建

### ISSUE THREAD

**Issue by 519711862** [dotnetcore/sharding-core#274]
![企业微信截图_17248147058492](https://github.com/user-attachments/assets/e55d6316-0a4d-4642-a7b4-ce3171415692)

**Comment by xuejmnet** [comment]
经测试发现Wafer_Id_Sque序列会在多个dbcontext中不断创建,所以目前来讲没有好的办法来处理,建议这边单独执行数据库脚本
```sql
CREATE SEQUENCE [My_Id_Sque] AS int START WITH 0 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE;

```

**Comment by 519711862** [comment]
好的，非常感谢
